//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccBudgetDetail
    {
        public int BudgetDetailId { get; set; }
        public int BudgetID { get; set; }
        public string AccHeadID { get; set; }
        public string Description { get; set; }
        public double Amount { get; set; }
    }
}
