//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccGeneralLedger
    {
        //public int AccountHeadID1 { get; set; }
        public int LedgerID { get; set; }
        public string TrnID { get; set; }
        public System.DateTime TrnDate { get; set; }
        public string VoucherNo { get; set; }
        public int CompanyID { get; set; }
        public int AccProjectID { get; set; }
        public int VoucherTypeID { get; set; }
        public int PaymentTypeID { get; set; }
        public int AccountHeadID { get; set; }
        public string Description { get; set; }
        public double Debit { get; set; }
        public double Credit { get; set; }
        public int QuarterID { get; set; }
        public int BudgetID { get; set; }
        public byte[] Voucher { get; set; }
        public Nullable<bool> Status { get; set; }
        public string Creator { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
        public string Modifier { get; set; }
        public Nullable<System.DateTime> ModificationDate { get; set; }
        public int AccountHeadID1 { get; set; }
    }
}
