//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccQuarterBudget
    {
        public int QBudgetID { get; set; }
        public Nullable<int> CompanyID { get; set; }
        public string Quarter { get; set; }
        public int BudgetID { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public double TotalAmount { get; set; }
    }
}
