//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccSupplierPayment
    {
        public int User_PaymentID { get; set; }
        public decimal Sys_PaymentID { get; set; }
        public Nullable<System.DateTime> Sys_Payment_Date { get; set; }
        public System.DateTime Payment_Date { get; set; }
        public int SupplierID { get; set; }
        public Nullable<decimal> DrAmount { get; set; }
        public Nullable<decimal> CrAmount { get; set; }
    }
}
