//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccType
    {
        //public int AccTypeID1 { get; set; }
        public int AccTypeID { get; set; }
        public int AccTypeID1 { get; set; }
        public int CompanyID { get; set; }
        public string AccTypeName { get; set; }
        public string Note { get; set; }
        public string Creator { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
        public string Modifier { get; set; }
        public Nullable<System.DateTime> ModificationDate { get; set; }
    }
}
