//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class CashBook
    {
        public System.DateTime TrnDate { get; set; }
        public decimal OpeningBalance { get; set; }
        public decimal ReceivedBalance { get; set; }
        public decimal PaymentBalance { get; set; }
        public int Status { get; set; }
        public string Note { get; set; }
    }
}
