//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChequeRegister
    {
        public int ChequeRegID { get; set; }
        public int CompanyID { get; set; }
        public string VoucherNo { get; set; }
        public System.DateTime TranDate { get; set; }
        public int BankID { get; set; }
        public string ChequeNo { get; set; }
        public int AccountID { get; set; }
        public string Description { get; set; }
        public decimal Amount { get; set; }
        public bool Status { get; set; }
        public int VoucherTypeID { get; set; }
    }
}
