//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class CRDRDetail
    {
        public int CRDRID { get; set; }
        public string ProductCode { get; set; }
        public decimal CRDRQty { get; set; }
        public decimal RatePerUnit { get; set; }
        public decimal SDAppPrice { get; set; }
        public decimal SD { get; set; }
        public decimal VATAppPrice { get; set; }
        public decimal VAT { get; set; }
    }
}
