//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerInfo
    {
        public int CustomerID { get; set; }
        public string CustomerCode { get; set; }
        public string CustomerName { get; set; }
        public string CustomerType { get; set; }
        public string Propietor { get; set; }
        public string ContactPerson { get; set; }
        public string Address { get; set; }
        public string DistrictID { get; set; }
        public string CountryID { get; set; }
        public string Phone { get; set; }
        public string Mobile { get; set; }
        public string eMail { get; set; }
        public string VATRegNo { get; set; }
        public string DiscountPercent { get; set; }
        public string DistributorPoint { get; set; }
        public bool Status { get; set; }
        public string Creator { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
        public string Modifier { get; set; }
        public Nullable<System.DateTime> ModificationDate { get; set; }
    }
}
