//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class PriceDeclarationDetail
    {
        public int DeclarationID { get; set; }
        public int SerialNo { get; set; }
        public string ProductCode { get; set; }
        public decimal UnitPrice { get; set; }
        public decimal GrossQty { get; set; }
        public decimal RequiredQty { get; set; }
        public decimal WastageQty { get; set; }
        public decimal ActualQty { get; set; }
        public decimal Amount { get; set; }
    }
}
