//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class PriceDeclarationInfo
    {
        public int DeclarationID { get; set; }
        public int SerialNo { get; set; }
        public System.DateTime Entrydate { get; set; }
        public string ProductCode { get; set; }
        public decimal UnitValue { get; set; }
        public decimal UnitPrice { get; set; }
        public string HSCode { get; set; }
        public decimal SDAmount { get; set; }
        public string VATType { get; set; }
        public decimal VATAmount { get; set; }
        public decimal SDCurrentPrice { get; set; }
        public decimal SDProposedPrice { get; set; }
        public decimal SDOnSDPrice { get; set; }
        public decimal VATCurrentPrice { get; set; }
        public decimal VATProposedPrice { get; set; }
        public decimal WholeSalePrice { get; set; }
        public decimal RetailPrice { get; set; }
        public string Creator { get; set; }
        public System.DateTime CreationDate { get; set; }
        public string Modifier { get; set; }
        public System.DateTime ModificationDate { get; set; }
        public int Active { get; set; }
    }
}
