//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class PriceDeclarationExpense
    {
        public int DeclarationID { get; set; }
        public int ExpenseID { get; set; }
        public int SLNO { get; set; }
        public string ExpenseCode { get; set; }
        public decimal Expense { get; set; }
    }
}
