//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductPrice
    {
        public decimal Sys_ID { get; set; }
        public string Inv_ProductID { get; set; }
        public Nullable<decimal> CostPrice { get; set; }
        public Nullable<decimal> Regular_MRP { get; set; }
        public Nullable<decimal> Dealer_MRP { get; set; }
        public Nullable<System.DateTime> EffectiveDate { get; set; }
        public string Modifier { get; set; }
        public Nullable<System.DateTime> ModificationDate { get; set; }
    }
}
