//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository
{
    using System;
    using System.Collections.Generic;
    using System.Web;
    
    public partial class ProductInfo
    {
        //public HttpPostedFileBase File { get; set; }
        public int ProductID { get; set; }
        public string ProductCode { get; set; }
        public string ProductName { get; set; }
        public string ProductType { get; set; }
        public int ProductCategoryID { get; set; }
        public int BrandID { get; set; }
        public Nullable<int> ColorID { get; set; }
        public Nullable<int> SizeID { get; set; }
        public int TarrifTypeID { get; set; }
        public int UnitID { get; set; }
        public int UnitIDOut { get; set; }
        public decimal ConversionRate { get; set; }
        public int VATTypeID { get; set; }
        public decimal WeightPerUnit { get; set; }
        public decimal RatePerUnit { get; set; }
        public decimal VATableRate { get; set; }
        public decimal VATPercent { get; set; }
        public decimal RebatePercent { get; set; }
        public decimal SDPercent { get; set; }
        public decimal SupTaxPercent { get; set; }
        public decimal ApprovedPrice { get; set; }
        public int ReorderLevel { get; set; }
        public byte[] ProductImage { get; set; }
        public string Note { get; set; }
        public string Creator { get; set; }
        public System.DateTime CreationDate { get; set; }
        public string Modifier { get; set; }
        public System.DateTime ModificationDate { get; set; }
        public System.DateTime EffectiveDate { get; set; }
        public bool Status { get; set; }
        public Nullable<decimal> CostPrice { get; set; }
        public Nullable<decimal> RegularMRP { get; set; }
        public HttpPostedFileBase File { get; set; }
    }
}
