//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class Purchase
    {
        public int PID { get; set; }
        public System.DateTime PurchaseDate { get; set; }
        public string PurchaseID { get; set; }
        public string GRNNo { get; set; }
        public decimal SupplierID { get; set; }
        public string InvoiceNo { get; set; }
        public System.DateTime InvoiceDate { get; set; }
        public string ChallanBENo { get; set; }
        public System.DateTime ChallanDate { get; set; }
        public string LCNo { get; set; }
        public System.DateTime LCDate { get; set; }
        public string PONo { get; set; }
        public System.DateTime PODate { get; set; }
        public string IsVoid { get; set; }
        public string Note { get; set; }
        public string Creator { get; set; }
        public System.DateTime CreationDate { get; set; }
        public string Modifier { get; set; }
        public System.DateTime ModificationDate { get; set; }
        public int Active { get; set; }
    }
}
