//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaxSource
    {
        public int SourceID { get; set; }
        public string SourceCode { get; set; }
        public string SourceName { get; set; }
        public decimal StartAmount { get; set; }
        public decimal EndAmount { get; set; }
        public decimal VATPercent { get; set; }
        public decimal Rebate { get; set; }
        public string SourceType { get; set; }
        public bool Status { get; set; }
        public string Creator { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
        public string Modifier { get; set; }
        public Nullable<System.DateTime> ModificationDate { get; set; }
    }
}
