//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class TreasuryPayment
    {
        public int PaymentID { get; set; }
        public string VPNo { get; set; }
        public Nullable<System.DateTime> PaymentDate { get; set; }
        public string EnterBy { get; set; }
        public System.DateTime CreationDate { get; set; }
        public string Modifier { get; set; }
        public System.DateTime ModificationDate { get; set; }
        public int Active { get; set; }
    }
}
