//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class vAccTrialBalance
    {
        public int AccHeadID { get; set; }
        public string AccountName { get; set; }
        public Nullable<double> SumofDebit { get; set; }
        public Nullable<double> SumofCredit { get; set; }
        public System.DateTime TrnDate { get; set; }
        public string Description { get; set; }
    }
}
