//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class vAccGeneralLedger
    {
        public System.DateTime TrnDate { get; set; }
        public string VoucherNo { get; set; }
        public string Description { get; set; }
        public double Debit { get; set; }
        public double Credit { get; set; }
        public int VoucherTypeID { get; set; }
        public double OpenDebitBalance { get; set; }
        public double OpenCreditBalance { get; set; }
        public bool Active { get; set; }
        public int CompanyID { get; set; }
        public string CompanyName { get; set; }
        public int AccHeadID { get; set; }
        public string AccountName { get; set; }
    }
}
